### ISSUE TITLE
Trying to rung CameraWithCVAndCalibration app

### ISSUE THREAD

**Issue by hein30** [microsoft/HoloLens2ForCV#44]
I am trying to run CameraWithCVAndCalibration sample app. But I am having trouble building the app. 

Error	LNK1107	invalid or corrupt file: cannot read at 0x86	CameraWithCVAndCalibration	C:\Users\xxx\Desktop\HoloLens2ForCV-main\Samples\CameraWithCVAndCalibration\OpenCvInstallArm64-412d\x64\vc15\staticlib\opencv_world412d.lib	1	

Could someone please elaborate on how to install opencv  for this project? Thanks

**Comment by DadEap** [comment]
I add the same error. It was because I downloaded the project as a zip.

The opencv static library is a heavy file which cannot be directly downloaded. To do so, you need to install git lfs (https://git-lfs.github.com/), which can handle large volume of data, and then clone the project. If the files located in "OpenCvInstallArm64-412d\x64\vc15\staticlib" have a size > 1 Ko, it should work.
